notional-finance/notional-monorepo

apps/web/src/containers/LandingPageView/components/Sections/FromTheBlogSection/index.tsx
apps/web/src/containers/LandingPageView/components/Sections/VentureCapitalPartners/index.tsx
package.json
packages/common/mui/src/lib/drawer/drawer.tsx
packages/common/mui/src/lib/side-drawer/side-drawer.tsx
packages/common/styles/src/lib/notional-theme/notional-theme.ts
packages/features/borrow/src/lib/borrow-sidebar/borrow-sidebar.tsx
packages/features/portfolio/src/components/empty-portfolio/empty-portfolio.tsx
packages/features/portfolio/src/components/index.ts
packages/features/portfolio/src/components/portfolio-mobile-nav/portfolio-mobile-nav.spec.tsx
packages/features/portfolio/src/components/portfolio-mobile-nav/portfolio-mobile-nav.tsx
packages/features/portfolio/src/components/portfolio-mobile-nav/use-portfolio-mobile-nav.tsx
packages/features/portfolio/src/portfolio-feature-shell.tsx
packages/shared/web/src/footer/footer.tsx
yarn.lock

- Adds portfolio mobile nav
- Updates mobile styling on portfolio page
- Updates mobile styling on empty portfolio component 
- Updates mobile styling on borrow page
- Hides footer on mobile
- Updates notional-theme break points, background color, and Caption font size
- Fixes SideDrawer swipe bug

build: adds portfolio mobile nav

---

packages/features/portfolio/src/components/portfolio-mobile-nav/portfolio-mobile-nav.tsx
packages/features/portfolio/src/components/side-nav/messages.tsx
packages/features/portfolio/src/components/side-nav/side-nav-options.tsx
packages/features/portfolio/src/components/side-nav/side-nav.tsx
packages/features/portfolio/src/hooks/use-side-nav.tsx
packages/features/portfolio/src/portfolio-feature-shell.tsx
packages/shared/web/src/footer/footer.tsx

- Adds portfolio SideNavOptions component
- Refactors portfolio SideNav
- Small fixes to portfolio mobile nav

build: adds side-nav-options/refactors side-nav

---

apps/web/src/containers/App/HeaderRenderer.js
packages/common/mui/src/lib/action-sidebar-buttons/action-sidebar-buttons.tsx
packages/shared/trade/src/transaction-confirmation/transaction-confirmation.tsx
packages/shared/wallet/src/connect-wallet-side-drawer/connect-wallet-side-drawer.tsx
packages/shared/wallet/src/settings-side-drawer/wallet-switcher/wallet-switcher.tsx
packages/shared/web/src/video-player-hero/video-player-hero.tsx

- Adds tracking for transaction submit and confirmation
- Adds tracking for wallet connections
- Adds tracking for video plays

build: add tracking for txns and wallet connections

---

apps/web/src/index.html

build: adds new meta image

---

packages/features/vault/src/side-drawers/components/vault-side-drawer.tsx
packages/features/vault/src/side-drawers/messages.tsx
packages/features/vault/src/side-drawers/withdraw-and-repay-debt/use-withdraw-and-repay-debt.ts
packages/features/vault/src/side-drawers/withdraw-and-repay-debt/withdraw-and-repay-debt.tsx
packages/notionable/src/leveraged-vaults/logic/get-withdraw-amount-data.ts

- Adds withdraw and repay debt side drawer
- Adds vault side drawer loading state

build: adds withdraw repay debt sidedrawer

---

apps/web/src/containers/App/layouts/AppLayoutRoute/index.js
apps/web/src/containers/LandingPageView/components/hero/hero.tsx
packages/common/mui/src/index.ts
packages/common/mui/src/lib/previous-ui-popup/previous-ui-popup.spec.tsx
packages/common/mui/src/lib/previous-ui-popup/previous-ui-popup.tsx
packages/shared/web/src/footer/footer.tsx

build: adds previous ui popup

---

packages/common/mui/src/lib/area-chart/area-chart.tsx
packages/common/mui/src/lib/data-table/data-table-body/data-table-body.tsx
packages/common/mui/src/lib/data-table/data-table-head/data-table-head.tsx
packages/common/mui/src/lib/data-table/types.ts
packages/features/vault/src/hooks/use-geoip-block.ts
packages/features/vault/src/hooks/use-performance-chart.tsx
packages/features/vault/src/messages.ts
packages/features/vault/src/vault-view/vault-summary.tsx
packages/shared/trade/src/trade-action-button/trade-action-button.tsx

- Updates area chart xAxis
- Updates area chart leveraged returns formatting
- Fixes connect wallet to trade button
- Adds new table variant

Bugfix/vault UI fixes

---

packages/common/mui/src/lib/typography/typography.tsx
packages/common/styles/src/lib/notional-theme/notional-theme.ts
packages/shared/web/src/card-container/card-mobile-nav/card-mobile-nav.tsx
packages/shared/web/src/card-container/card-table/card-table.tsx

- fixes mobile bugs on card page

build: fixes mobile bugs on card page

---

packages/common/mui/src/lib/area-chart/area-chart.tsx
packages/features/liquidity/src/liquidity-cards.tsx
packages/shared/web/src/card-container/card-container.tsx
packages/shared/web/src/card-container/card-sub-nav/card-sub-nav.tsx

build: updates styles based on feedback

---

apps/web/src/containers/LandingPageView/components/hero/hero.tsx
apps/web/src/containers/LandingPageView/components/multidisciplinary-security-approach/multidisciplinary-security-approach.tsx
apps/web/src/containers/LandingPageView/components/with-notional-you-can/with-notional-you-can.tsx
packages/common/mui/src/lib/interactive-area-chart/interactive-area-chart.tsx
packages/common/mui/src/lib/interactive-area-chart/x-axis-date-tick/x-axis-date-tick.tsx
packages/common/mui/src/lib/typography/typography.tsx
packages/features/portfolio/src/portfolio-feature-shell.tsx
packages/features/vault/src/components/vault-sub-nav/vault-sub-nav.tsx
packages/shared/web/src/card-container/card-table/card-table.tsx
packages/shared/web/src/card-container/card-table/risk-score-indicator/risk-score-indicator.tsx
packages/shared/web/src/landing-footer/landing-footer.tsx

- Fixes vault page back to top button error
- Fixes many small console errors
- Fixes XAxisDateTick error
- Fixes descendent of p tag error
- Fixes scroll height bug on portfolio page

build: fixes errors

---

packages/common/mui/src/lib/currency-input/currency-input.tsx
packages/common/mui/src/lib/data-table-cells/chevron-cell/chevron-cell.tsx
packages/common/mui/src/lib/maturity-card/maturity-card.tsx
packages/common/mui/src/lib/side-bar-sub-header/side-bar-sub-header.tsx
packages/shared/wallet/src/settings-side-drawer/wallet-switcher/wallet-switcher.tsx

- Fixes view as account / disconnect wallet bug
- Fixes table dropdown arrow hover bug
- Fixes input background color bug

build: fixes style bugs

---

packages/notionable/src/onboard/onboard-manager.ts

- Testing if the wallet object from onboard is not arriving on time and causing this issue
- Possible fix of using the label string prop instead of the wallet.label

build: connect wallet testing

---

apps/web/src/containers/LandingPageView/components/hero/hero.tsx

build: removes lottie on smallest screen size

---

apps/web/src/containers/LandingPageView/components/how-it-works/components/card.tsx
packages/features/portfolio/src/portfolio-feature-shell.tsx
packages/features/vault/src/components/vault-sub-nav/use-vault-sub-nav.tsx
packages/features/vault/src/components/vault-sub-nav/vault-sub-nav.tsx
packages/features/vault/src/vault-view/vault-action-side-drawer.tsx
packages/notionable/src/leveraged-vaults/logic/get-init-vault-action.ts
packages/notionable/src/leveraged-vaults/vault-action-manager.ts

- Fixes vault sub nav bug
- Fixes portfolio screens not opening at the top
- Fixes Vault Details table not updating when coming from the Manage Vault side drawer in Portfolio

Bugfix/beta UI issues

---

packages/sdk/src/Notional.ts

Reverts notional-finance/notional-monorepo#169

Revert "build: bumping sdk logging"

---

yarn.lock

- Upgrades @tryghost/content-api

build: updates ghost-api package

---

packages/features/stake/src/stake-action/stake-action.tsx
packages/features/stake/src/stake-action/stake-store.ts

build: fixes stake bug

---

packages/features/lend/src/lend-sidebar/lend-balance-info.tsx
packages/features/lend/src/store/use-balance-info.ts
packages/features/lend/src/store/use-lend-transaction.ts
packages/features/vault/src/components/vault-side-drawer.tsx
packages/features/vault/src/vault-view/vault-action-side-drawer.tsx
packages/shared/trade/src/lend-borrow-input/use-lend-borrow-input.tsx

- Fixes token allowance bug to show error message on and and borrow screens when the allowance is too low
- Fixes vault geo blocker bug not working
- Fixes style bug related to CreateVaultPosition

build: fixes vault and token allowance bugs

---

packages/common/icons/src/lib/lightning-icon/lightning-icon.tsx
packages/common/mui/src/lib/action-sidebar/action-sidebar.tsx
packages/features/lend/src/lend-fixed/components/lend-fixed-sidebar.tsx
packages/features/lend/src/lend-fixed/lend-fixed.tsx
packages/features/lend/src/lend-variable/components/lend-variable-sidebar.tsx
packages/features/lend/src/lend-variable/hooks/use-lend-variable-faq.tsx
packages/features/lend/src/lend-variable/lend-variable.tsx
packages/features/liquidity/src/components/liquidity-sidebar.tsx
packages/features/vault/src/components/vault-side-drawer.tsx
packages/features/vault/src/vault-view/vault-action-provider.tsx
packages/notionable/src/base-trade/trade-manager.ts
packages/shared/notionable-hooks/src/observable-context/BaseTradeContext.tsx
packages/shared/notionable-hooks/src/observable-context/ObservableContext.tsx

- Refactors txn confirmation flow to use context instead of URL query
- Makes cancel button work on txn confirmation
- Updates Faq to include tokenSymbol
- Fixes other small bugs

build: fixes txn sidebar bugs

---

packages/features/portfolio/src/components/portfolio-mobile-nav/portfolio-mobile-nav.tsx

- Removes swipe from portfolio mobile nav

build: updates portfolio mobile nav

---

apps/web/src/containers/TradingContest/contest-leader-board/contest-leader-board.tsx
apps/web/src/containers/TradingContest/hooks/use-compact-tables.tsx
apps/web/src/containers/TradingContest/hooks/use-leaderboard-data.ts
apps/web/src/containers/TradingContest/hooks/use-leaderboard-tables.tsx
packages/common/mui/src/lib/contest-table/contest-cells/custom-icon-cell.tsx
packages/common/mui/src/lib/contest-table/contest-table.tsx
packages/shared/wallet/src/images/rabby.svg
packages/shared/wallet/src/onboard-context.tsx

- Adds rabby wallet option
- Adds address copy option to contest table cell
- Update empty text color and value to no entrants on contest table

build: updates custom icon cell

---

apps/web/src/containers/TradingContest/components/contest-countdown/contest-countdown.tsx
apps/web/src/containers/TradingContest/hooks/use-contest-rules-info.tsx

- Updates contest timer to 10/25/23 midnight est time

build: updates timer

---

packages/common/mui/src/lib/card-variants/currency-fixed/currency-fixed.tsx
packages/common/mui/src/lib/card-variants/incentive-active/incentive-active.tsx
packages/common/mui/src/lib/card-variants/incentive-leveraged/incentive-leveraged.tsx
packages/common/mui/src/lib/card-variants/incentive/incentive.tsx
packages/common/mui/src/lib/card-variants/index.ts
packages/common/mui/src/lib/card-variants/vault/vault.tsx
packages/common/mui/src/lib/chart-header-totals/chart-header-totals.tsx
packages/common/styles/src/lib/notional-theme/notional-theme.ts
packages/core-entities/src/Definitions.ts
packages/features/liquidity/src/cards.tsx
packages/features/portfolio/src/containers/portfolio-overview/hooks/use-totals-chart.tsx
packages/features/vault/src/vault-card-view.tsx
packages/shared/helpers/src/number-helpers.ts

- Adds current APY to portfolio overview chart
- Updates leveraged liquidity cards
- Updates vault cards

build: adds leverage liquidity cards

---

packages/common/mui/src/lib/data-table/data-table-body/data-table-body.tsx
packages/common/mui/src/lib/data-table/data-table-head/data-table-head.tsx
packages/common/mui/src/lib/data-table/data-table.tsx
packages/risk-engine/src/account-risk.ts
packages/shared/trade/src/transaction-sidebar/components/liquidation-risk.tsx

build: fixes table bugs

---

packages/common/mui/src/lib/data-table-cells/multi-value-icon-cell/multi-value-icon-cell.tsx
packages/common/mui/src/lib/data-table/data-table-body/data-table-body.tsx
packages/features/portfolio/src/components/side-nav/side-nav-options.tsx
packages/features/portfolio/src/components/total-earnings-tooltip/total-earnings-tooltip.tsx
packages/features/portfolio/src/containers/portfolio-holdings/portfolio-holdings.tsx
packages/features/portfolio/src/containers/portfolio-holdings/use-detailed-holdings.tsx

- Lightning bolt change
- Add divider line above Total row in Portfolio Holdings table
- Total Earnings in Total row should reflect NOTE incentives as well as organic earnings
- Updates width of portfolio side nav notification dot

build: adds portfolio fixes

---

packages/common/mui/src/lib/slider-basic/slider-basic.tsx
packages/common/mui/src/lib/slider-input/slider-input.tsx
packages/features/liquidity/src/liquidity-leveraged/components/liquidity-terms.tsx
packages/features/liquidity/src/liquidity-leveraged/side-drawers/adjust-leverage.tsx
packages/features/vault/src/components/vault-leverage-slider.tsx
packages/features/vault/src/components/vault-sub-nav/vault-sub-nav.tsx
packages/shared/trade/src/leverage-slider/leverage-slider.tsx

- Adds min value to slider
- Adds min max slider ticks

build: adds min value and ticks

---

packages/features/portfolio/src/side-drawers/convert-asset.tsx
packages/features/portfolio/src/side-drawers/roll-debt.tsx
packages/shared/trade/src/hooks/use-max-repay.tsx
packages/shared/trade/src/transaction-confirmation/components/transaction-buttons.tsx

- Removes unneeded error in token approval flow
- Makes transaction confirmation buttons fixed on small screens
- Prevents maturity options disappearing relating to convert-asset/roll-debt

build: fixes bugs

---

packages/common/mui/src/lib/card-variants/vault/vault.tsx

- Fixes styled bug that causes card to be longer than overlay

build: fixes vault card bug

---

packages/common/mui/src/lib/card-variants/currency-fixed/currency-fixed.tsx

- Fixed overflow bug on fixed cards

build: fixes overflow

---

packages/core-entities/src/client/configuration-client.ts
packages/features/lend/src/lend-fixed/components/lend-fixed-trade-summary.tsx
packages/features/lend/src/lend-fixed/hooks/use-totals-data.tsx
packages/features/liquidity/src/liquidity-leveraged/hooks/index.ts
packages/features/liquidity/src/liquidity-leveraged/hooks/use-totals-data.tsx
packages/features/liquidity/src/liquidity-leveraged/liquidity-leveraged-summary.tsx
packages/shared/notionable-hooks/src/use-market.ts
packages/shared/trade/src/hooks/use-variable-totals.tsx

- Adds capacity remaining to total box row of Lend Fixed, Lend Variable, Provide Liquidity and Leveraged Liquidity

build: adds capacity remaining values

---

packages/common/mui/src/lib/data-table/data-table-body/data-table-body.tsx
packages/features/portfolio/src/hooks/use-portfolio-button-bar.tsx
packages/features/portfolio/src/side-drawers/deposit-collateral.tsx
packages/features/portfolio/src/side-drawers/withdraw.tsx

- Fixes Top 3 portfolio buttons are non-responsive
- Fixes "view" links are broken on markets page
- Fixes Deposit Collateral Drawer Broken
- Fixes Withdraw drawer broken on portfolio

build: fixes portfolio side drawer bugs and markets table links

---

packages/common/mui/src/lib/product-dashboard/components/dashboard-header.tsx
packages/common/mui/src/lib/product-dashboard/components/index.ts
packages/common/mui/src/lib/product-dashboard/components/leveraged-card.tsx
packages/common/mui/src/lib/product-dashboard/components/leveraged-dashboard.tsx
packages/common/mui/src/lib/product-dashboard/product-dashboard.tsx
packages/features/vault/src/hooks/use-vault-cards.tsx
packages/shared/wallet/src/connect-wallet-side-drawer/connect-wallet-side-drawer.tsx
packages/shared/web/src/header/header.tsx
packages/shared/web/src/header/mobile-navigation/mobile-navigation.tsx

- Updates vault grid card values
- Fixes mobile nav bug

build: updates vault dashboard grid card data

---

apps/web/src/containers/LandingPageView/components/hero/components/hero-content.tsx
packages/common/mui/src/lib/bar-chart/bar-chart-tool-tip/bar-chart-tool-tip.tsx
packages/common/mui/src/lib/product-dashboard/components/dashboard-header.tsx
packages/common/mui/src/lib/product-dashboard/product-dashboard.tsx
packages/common/mui/src/lib/trade-action-title/trade-action-title.tsx
packages/features/liquidity/src/liquidity-variable/hooks/use-apy-chart.tsx
packages/features/liquidity/src/liquidity-variable/hooks/use-totals-data.tsx
packages/shared/trade/src/trade-action-summary/components/index.ts
packages/shared/trade/src/trade-action-summary/components/liquidity-yield-info.tsx
packages/shared/trade/src/trade-action-summary/components/native-yield-popup.tsx
packages/shared/trade/src/trade-action-summary/trade-action-summary.tsx
packages/shared/web/src/dashboard-view/dashboard-view.tsx
packages/shared/web/src/dashboard-view/hooks/use-lend-borrow-list.tsx
packages/shared/web/src/dashboard-view/hooks/use-liquidity-list.tsx
packages/shared/web/src/dashboard-view/hooks/use-vault-list.tsx
packages/shared/web/src/dashboard-view/hooks/utils.ts
packages/shared/web/src/header/borrow-dropdown/use-borrow-dropdown.tsx
packages/shared/web/src/header/invest-and-earn/use-invest-earn-links.tsx
packages/shared/web/src/header/launch-app-button/launch-app-button.tsx
packages/util/src/constants.ts

- Fixes launch app button bugs
- Fixes nav dropdown network bugs
- Fixes nToken APY chart to only show organic apy when mainnet is selected

build: fixes issues related to ntoken apy chart and mainnet

---

apps/data/wrangler.toml
apps/registry-tokens/wrangler.toml
apps/rewards/src/index.ts

4pool requires gas limit above default values

fix: increase default gas limit on simulations
